/** IPC channel names, centralized so both sides agree. */
export const IPC = {
  // renderer -> main (invoke)
  TAB_CREATE: 'tab:create',
  TAB_CLOSE: 'tab:close',
  TAB_SWITCH: 'tab:switch',
  TAB_NAVIGATE: 'tab:navigate',
  TAB_BACK: 'tab:back',
  TAB_FORWARD: 'tab:forward',
  TAB_CAPTURE: 'tab:capture',
  APP_CAPTURE: 'app:capture',
  TAB_RELOAD: 'tab:reload',
  TAB_REORDER: 'tab:reorder',
  TAB_LIST: 'tab:list',
  LAYOUT_SET_BOUNDS: 'layout:setBounds',
  CDP_SEND: 'cdp:send',
  CHAT_SEND: 'chat:send',
  CHAT_ABORT: 'chat:abort',
  KEYS_STATUS: 'keys:status',
  KEYS_SET: 'keys:set',
  CODEX_STATUS: 'codex:status',
  CODEX_MODELS: 'codex:models',
  WORKSPACE_GET: 'workspace:get',
  WORKSPACE_SET_FOLDER: 'workspace:setFolder',
  WORKSPACE_PICK_FOLDER: 'workspace:pickFolder',
  AUDIT_LIST: 'audit:list',
  CHATS_LIST: 'chats:list',
  CHATS_GET: 'chats:get',
  CHATS_SAVE: 'chats:save',
  CHATS_SAVE_SYNC: 'chats:saveSync',
  CHATS_DELETE: 'chats:delete',
  CHATS_LAST_ACTIVE: 'chats:lastActive',
  CHATS_TITLE: 'chats:title',
  CHATS_SEARCH: 'chats:search',
  EXTRACT_RUN: 'extract:run',
  EXTRACT_OVERLAY: 'extract:overlay',
  BROWSER_EXEC: 'browser:exec',
  /** Text-to-speech: renderer sends text, main returns synthesized audio. */
  TTS_SPEAK: 'tts:speak',
  // main -> renderer (send)
  TABS_UPDATED: 'tabs:updated',
  CDP_EVENT: 'cdp:event',
  CHAT_STREAM: 'chat:stream',
  AUDIT_EVENT: 'audit:event'
} as const
