/** IPC channel names, centralized so both sides agree. */
export const IPC = {
  // renderer -> main (invoke)
  TAB_CREATE: 'tab:create',
  TAB_CLOSE: 'tab:close',
  TAB_SWITCH: 'tab:switch',
  TAB_NAVIGATE: 'tab:navigate',
  TAB_BACK: 'tab:back',
  TAB_FORWARD: 'tab:forward',
  TAB_CAPTURE: 'tab:capture',
  APP_CAPTURE: 'app:capture',
  TAB_RELOAD: 'tab:reload',
  TAB_REORDER: 'tab:reorder',
  TAB_LIST: 'tab:list',
  LAYOUT_SET_BOUNDS: 'layout:setBounds',
  CDP_SEND: 'cdp:send',
  CHAT_SEND: 'chat:send',
  CHAT_ABORT: 'chat:abort',
  KEYS_STATUS: 'keys:status',
  KEYS_SET: 'keys:set',
  CODEX_STATUS: 'codex:status',
  CODEX_MODELS: 'codex:models',
  WORKSPACE_GET: 'workspace:get',
  WORKSPACE_SET_FOLDER: 'workspace:setFolder',
  WORKSPACE_PICK_FOLDER: 'workspace:pickFolder',
  AUDIT_LIST: 'audit:list',
  CHATS_LIST: 'chats:list',
  CHATS_GET: 'chats:get',
  CHATS_SAVE: 'chats:save',
  CHATS_SAVE_SYNC: 'chats:saveSync',
  CHATS_DELETE: 'chats:delete',
  CHATS_LAST_ACTIVE: 'chats:lastActive',
  CHATS_TITLE: 'chats:title',
  CHATS_SEARCH: 'chats:search',
  EXTRACT_RUN: 'extract:run',
  EXTRACT_OVERLAY: 'extract:overlay',
  BROWSER_EXEC: 'browser:exec',
  // Memory "Dreaming" — manual-trigger background memory curator
  DREAM_RUN: 'dream:run',
  DREAM_LOAD_LAST: 'dream:loadLast',
  DREAM_ADOPT: 'dream:adopt',
  DREAM_DISCARD: 'dream:discard',
  DREAM_STATUS: 'dream:status',
  /** main → renderer push: stage-by-stage progress while a dream runs. */
  DREAM_PROGRESS: 'dream:progress',
  /** Text-to-speech: renderer sends text, main returns synthesized audio. */
  TTS_SPEAK: 'tts:speak',
  // Real-PTY terminal (xterm.js <-> @lydell/node-pty in main)
  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_KILL: 'terminal:kill',
  TERMINAL_SET_CWD: 'terminal:setCwd',
  // main -> renderer (send)
  TABS_UPDATED: 'tabs:updated',
  CDP_EVENT: 'cdp:event',
  CHAT_STREAM: 'chat:stream',
  AUDIT_EVENT: 'audit:event',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit'
} as const
